In [1]:
import pandas as pd
print("successful")

successful

In [2]:
df=pd.read_csv("train.csv")
print(df)

      Customer ID               Name Gender  Age  Income (USD)  \
0         C-36995   Frederica Shealy      F   56       1933.05
1         C-33999  America Calderone      M   32       4952.91
2          C-3770      Rosetta Verne      F   65        988.19
3         C-26480         Zoe Chitty      F   65           NaN
4         C-23459       Afton Venema      F   31       2614.77
...           ...                ...    ...  ...           ...
29995     C-43723  Angelyn Clevenger      M   38       4969.41
29996     C-32511       Silas Slaugh      M   20       1606.88
29997      C-5192       Carmelo Lone      F   49           NaN
29998     C-12172      Carolann Osby      M   38       2417.71
29999     C-33003  Bridget Garibaldi      F   63       3068.24

      Income Stability            Profession     Type of Employment  \
0                  Low               Working            Sales staff
1                  Low               Working                    NaN
2                 High             Pensioner                    NaN
3                 High             Pensioner                    NaN
4                  Low               Working  High skill tech staff
...                ...                   ...                    ...
29995              Low  Commercial associate               Managers
29996              Low               Working               Laborers
29997              Low               Working            Sales staff
29998              Low               Working         Security staff
29999             High             Pensioner                    NaN

         Location  Loan Amount Request (USD)  ...  Credit Score  \
0      Semi-Urban                   72809.58  ...        809.44
1      Semi-Urban                   46837.47  ...        780.40
2      Semi-Urban                   45593.04  ...        833.15
3           Rural                   80057.92  ...        832.70
4      Semi-Urban                  113858.89  ...        745.55
...           ...                        ...  ...           ...
29995       Urban                   76657.90  ...        869.61
29996  Semi-Urban                   66595.14  ...        729.41
29997       Urban                   81410.08  ...           NaN
29998  Semi-Urban                  142524.10  ...        677.27
29999       Rural                  156290.54  ...        815.44

      No. of Defaults Has Active Credit Card  Property ID  Property Age  \
0                   0                    NaN          746       1933.05
1                   0            Unpossessed          608       4952.91
2                   0            Unpossessed          546        988.19
3                   1            Unpossessed          890           NaN
4                   1                 Active          715       2614.77
...               ...                    ...          ...           ...
29995               0            Unpossessed          566       4969.41
29996               0               Inactive          175       1606.88
29997               0                 Active          959           NaN
29998               1            Unpossessed          375       2417.71
29999               0                 Active          344       3068.24

       Property Type Property Location  Co-Applicant  Property Price  \
0                  4             Rural             1       119933.46
1                  2             Rural             1        54791.00
2                  2             Urban             0        72440.58
3                  2        Semi-Urban             1       121441.51
4                  4        Semi-Urban             1       208567.91
...              ...               ...           ...             ...
29995              4             Urban             1       111096.56
29996              3             Urban             1        73453.94
29997              1             Rural             1       102108.02
29998              4             Urban             1       168194.47
29999              3             Rural             1       194512.60

       Loan Sanction Amount (USD)
0                        54607.18
1                        37469.98
2                        36474.43
3                        56040.54
4                        74008.28
...                           ...
29995                    68992.11
29996                    46616.60
29997                    61057.56
29998                    99766.87
29999                   117217.90

[30000 rows x 24 columns]

In [3]:
df.columns

Index(['Customer ID', 'Name', 'Gender', 'Age', 'Income (USD)',
       'Income Stability', 'Profession', 'Type of Employment', 'Location',
       'Loan Amount Request (USD)', 'Current Loan Expenses (USD)',
       'Expense Type 1', 'Expense Type 2', 'Dependents', 'Credit Score',
       'No. of Defaults', 'Has Active Credit Card', 'Property ID',
       'Property Age', 'Property Type', 'Property Location', 'Co-Applicant',
       'Property Price', 'Loan Sanction Amount (USD)'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer ID                  30000 non-null  str
 1   Name                         30000 non-null  str
 2   Gender                       29947 non-null  str
 3   Age                          30000 non-null  int64
 4   Income (USD)                 25424 non-null  float64
 5   Income Stability             28317 non-null  str
 6   Profession                   30000 non-null  str
 7   Type of Employment           22730 non-null  str
 8   Location                     30000 non-null  str
 9   Loan Amount Request (USD)    30000 non-null  float64
 10  Current Loan Expenses (USD)  29828 non-null  float64
 11  Expense Type 1               30000 non-null  str
 12  Expense Type 2               30000 non-null  str
 13  Dependents                   27507 non-null  float64
 14  Credit Score                 28297 non-null  float64
 15  No. of Defaults              30000 non-null  int64
 16  Has Active Credit Card       28434 non-null  str
 17  Property ID                  30000 non-null  int64
 18  Property Age                 25150 non-null  float64
 19  Property Type                30000 non-null  int64
 20  Property Location            29644 non-null  str
 21  Co-Applicant                 30000 non-null  int64
 22  Property Price               30000 non-null  float64
 23  Loan Sanction Amount (USD)   29660 non-null  float64
dtypes: float64(8), int64(5), str(11)
memory usage: 5.5 MB

In [5]:
df.describe()

,Age,Income (USD),Loan Amount Request (USD),Current Loan Expenses (USD),Dependents,Credit Score,No. of Defaults,Property ID,Property Age,Property Type,Co-Applicant,Property Price,Loan Sanction Amount (USD)
count,30000.000000,2.542400e+04,30000.000000,29828.000000,27507.000000,28297.000000,30000.000000,30000.000000,2.515000e+04,30000.000000,30000.000000,3.000000e+04,29660.000000
mean,40.092300,2.630574e+03,88826.333855,400.936876,2.253027,739.885381,0.193933,501.934700,2.631119e+03,2.460067,-4.743867,1.317597e+05,47649.342208
std,16.045129,1.126272e+04,59536.949605,242.545375,0.951162,72.163846,0.395384,288.158086,1.132268e+04,1.118562,74.614593,9.354955e+04,48221.146686
min,18.000000,3.777000e+02,6048.240000,-999.000000,1.000000,580.000000,0.000000,1.000000,3.777000e+02,1.000000,-999.000000,-9.990000e+02,-999.000000
25%,25.000000,1.650457e+03,41177.755000,247.667500,2.000000,681.880000,0.000000,251.000000,1.650450e+03,1.000000,1.000000,6.057216e+04,0.000000
50%,40.000000,2.222435e+03,75128.075000,375.205000,2.000000,739.820000,0.000000,504.000000,2.223250e+03,2.000000,1.000000,1.099936e+05,35209.395000
75%,55.000000,3.090593e+03,119964.605000,521.292500,3.000000,799.120000,0.000000,751.000000,3.091408e+03,3.000000,1.000000,1.788807e+05,74261.250000
max,65.000000,1.777460e+06,621497.820000,3840.880000,14.000000,896.260000,1.000000,999.000000,1.777460e+06,4.000000,1.000000,1.077967e+06,481907.320000

In [6]:
df.head(8)

,Customer ID,Name,Gender,Age,Income (USD),Income Stability,Profession,Type of Employment,Location,Loan Amount Request (USD),...,Credit Score,No. of Defaults,Has Active Credit Card,Property ID,Property Age,Property Type,Property Location,Co-Applicant,Property Price,Loan Sanction Amount (USD)
0,C-36995,Frederica Shealy,F,56,1933.05,Low,Working,Sales staff,Semi-Urban,72809.58,...,809.44,0,NaN,746,1933.05,4,Rural,1,119933.46,54607.18
1,C-33999,America Calderone,M,32,4952.91,Low,Working,NaN,Semi-Urban,46837.47,...,780.40,0,Unpossessed,608,4952.91,2,Rural,1,54791.00,37469.98
2,C-3770,Rosetta Verne,F,65,988.19,High,Pensioner,NaN,Semi-Urban,45593.04,...,833.15,0,Unpossessed,546,988.19,2,Urban,0,72440.58,36474.43
3,C-26480,Zoe Chitty,F,65,NaN,High,Pensioner,NaN,Rural,80057.92,...,832.70,1,Unpossessed,890,NaN,2,Semi-Urban,1,121441.51,56040.54
4,C-23459,Afton Venema,F,31,2614.77,Low,Working,High skill tech staff,Semi-Urban,113858.89,...,745.55,1,Active,715,2614.77,4,Semi-Urban,1,208567.91,74008.28
5,C-17688,Polly Crumpler,F,60,1234.92,Low,State servant,Secretaries,Rural,34434.72,...,684.12,1,Inactive,491,1234.92,2,Rural,1,43146.82,22382.57
6,C-23855,Nathalie Olivier,M,43,2361.56,Low,Working,Laborers,Semi-Urban,152561.34,...,637.29,0,Unpossessed,227,2361.56,1,Semi-Urban,1,221050.80,0.00
7,C-11006,Clarinda Montana,F,45,NaN,Low,State servant,Managers,Semi-Urban,240311.77,...,812.26,0,Active,314,NaN,2,Urban,1,401040.70,168218.24

In [7]:
print(df.duplicated().sum())

0

In [8]:
df.isnull().sum()

Customer ID                       0
Name                              0
Gender                           53
Age                               0
Income (USD)                   4576
Income Stability               1683
Profession                        0
Type of Employment             7270
Location                          0
Loan Amount Request (USD)         0
Current Loan Expenses (USD)     172
Expense Type 1                    0
Expense Type 2                    0
Dependents                     2493
Credit Score                   1703
No. of Defaults                   0
Has Active Credit Card         1566
Property ID                       0
Property Age                   4850
Property Type                     0
Property Location               356
Co-Applicant                      0
Property Price                    0
Loan Sanction Amount (USD)      340
dtype: int64

In [9]:
num_colmn = df.select_dtypes(
include=["int64", "float64"]
).columns.tolist()

In [10]:
print(num_colmn)

['Age', 'Income (USD)', 'Loan Amount Request (USD)', 'Current Loan Expenses (USD)', 'Dependents', 'Credit Score', 'No. of Defaults', 'Property ID', 'Property Age', 'Property Type', 'Co-Applicant', 'Property Price', 'Loan Sanction Amount (USD)']

In [11]:
cat_columns=df.select_dtypes(
    include="object").columns.tolist()

C:\Users\Naveenkumar\AppData\Local\Temp\ipykernel_13100\999842017.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns=df.select_dtypes(

In [12]:
print(cat_columns)

['Customer ID', 'Name', 'Gender', 'Income Stability', 'Profession', 'Type of Employment', 'Location', 'Expense Type 1', 'Expense Type 2', 'Has Active Credit Card', 'Property Location']

In [13]:
df["Property Age"]=df["Property Age"].fillna(df["Property Age"].mean())

In [14]:
print(df["Property Age"].isnull().sum())

0

In [15]:
print(df[num_colmn].isnull().sum())

Age                               0
Income (USD)                   4576
Loan Amount Request (USD)         0
Current Loan Expenses (USD)     172
Dependents                     2493
Credit Score                   1703
No. of Defaults                   0
Property ID                       0
Property Age                      0
Property Type                     0
Co-Applicant                      0
Property Price                    0
Loan Sanction Amount (USD)      340
dtype: int64

In [16]:
print(df[cat_columns].isnull().sum())

Customer ID                  0
Name                         0
Gender                      53
Income Stability          1683
Profession                   0
Type of Employment        7270
Location                     0
Expense Type 1               0
Expense Type 2               0
Has Active Credit Card    1566
Property Location          356
dtype: int64

In [17]:
from sklearn.impute import SimpleImputer
num_imp=SimpleImputer(strategy="median")
df[num_colmn]=num_imp.fit_transform(df[num_colmn])

cat_imp=SimpleImputer(strategy="most_frequent")
df[cat_columns]=cat_imp.fit_transform(df[cat_columns])

In [18]:
print(df.isnull().sum())

Customer ID                    0
Name                           0
Gender                         0
Age                            0
Income (USD)                   0
Income Stability               0
Profession                     0
Type of Employment             0
Location                       0
Loan Amount Request (USD)      0
Current Loan Expenses (USD)    0
Expense Type 1                 0
Expense Type 2                 0
Dependents                     0
Credit Score                   0
No. of Defaults                0
Has Active Credit Card         0
Property ID                    0
Property Age                   0
Property Type                  0
Property Location              0
Co-Applicant                   0
Property Price                 0
Loan Sanction Amount (USD)     0
dtype: int64

In [19]:
X=df.drop(columns=["Loan Sanction Amount (USD)"])
y=df["Loan Sanction Amount (USD)"]

In [20]:
print(X.shape)

(30000, 23)

In [21]:
print(y.shape)

(30000,)

In [22]:
X.head()

,Customer ID,Name,Gender,Age,Income (USD),Income Stability,Profession,Type of Employment,Location,Loan Amount Request (USD),...,Dependents,Credit Score,No. of Defaults,Has Active Credit Card,Property ID,Property Age,Property Type,Property Location,Co-Applicant,Property Price
0,C-36995,Frederica Shealy,F,56.0,1933.050,Low,Working,Sales staff,Semi-Urban,72809.58,...,3.0,809.44,0.0,Active,746.0,1933.05000,4.0,Rural,1.0,119933.46
1,C-33999,America Calderone,M,32.0,4952.910,Low,Working,Laborers,Semi-Urban,46837.47,...,1.0,780.40,0.0,Unpossessed,608.0,4952.91000,2.0,Rural,1.0,54791.00
2,C-3770,Rosetta Verne,F,65.0,988.190,High,Pensioner,Laborers,Semi-Urban,45593.04,...,1.0,833.15,0.0,Unpossessed,546.0,988.19000,2.0,Urban,0.0,72440.58
3,C-26480,Zoe Chitty,F,65.0,2222.435,High,Pensioner,Laborers,Rural,80057.92,...,2.0,832.70,1.0,Unpossessed,890.0,2631.11944,2.0,Semi-Urban,1.0,121441.51
4,C-23459,Afton Venema,F,31.0,2614.770,Low,Working,High skill tech staff,Semi-Urban,113858.89,...,2.0,745.55,1.0,Active,715.0,2614.77000,4.0,Semi-Urban,1.0,208567.91

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
print(X_train.shape)

(24000, 23)

In [25]:
print(y_train.shape)

(24000,)

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

number=X_train.select_dtypes(include="number").columns
cate=X_train.select_dtypes(include=["object","str"]).columns

preprocessor=ColumnTransformer([
    ("num",StandardScaler(),number),
    ("cat",OneHotEncoder(handle_unknown="ignore"),cate)
])
X_train_encoded=preprocessor.fit_transform(X_train)
X_test_encoded=preprocessor.transform(X_test)

In [27]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso

model=LinearRegression()
model.fit(X_train_encoded,y_train)
y_pred_lr=model.predict(X_test_encoded)

print(y_pred_lr)

[ 15758.07596684  39749.11225517  66374.8893729  ...  51891.21120337
    244.17923194 123670.72509575]

In [28]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error
import numpy as np

print(r2_score(y_test,y_pred_lr))
print(mean_squared_error(y_test, y_pred_lr))
print(mean_absolute_error(y_test, y_pred_lr))
print(np.sqrt(mean_squared_error(y_test, y_pred_lr)))

0.5574632265840762
1018081818.1353457
21780.917948051763
31907.394411567762

In [29]:
ridge=Ridge(alpha=0.1)
ridge.fit(X_train_encoded,y_train)
y_pred_rd=ridge.predict(X_test_encoded)
print(y_pred_rd)

[ 15743.24723797  39736.99313883  66382.646712   ...  51894.11710662
    243.55613326 123664.88976581]

In [30]:
print(r2_score(y_test,y_pred_rd))
print(mean_squared_error(y_test, y_pred_rd))
print(mean_absolute_error(y_test, y_pred_rd))
print(np.sqrt(mean_squared_error(y_test, y_pred_rd)))

0.5572917182870378
1018476383.0378878
21781.26854689897
31913.576782270706

In [35]:
print("hello")

hello

In [36]:
print("hi hello what is the problem please solve it")

hi hello what is the problem please solve it

In [39]:
from sklearn.model_selection import cross_val_score

scores=cross_val_score(
    LinearRegression(),
    X=X_train_encoded,
    y=y_train,
    cv=5,
    scoring="r2"
)
print(scores)

[0.57436225 0.53989944 0.58094498 0.56532463 0.61483096]

In [40]:
from sklearn.tree import DecisionTreeRegressor
print("imported")

imported

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

# Removed 'absolute_error' (which causes the freeze)
# Used parameters that calculate in seconds
param_grid = {
    'criterion': ['squared_error', 'friedman_mse'],
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10]
}

grid = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=1  # Uses ALL CPU cores
)

grid.fit(X_train_encoded, y_train)

best_model = grid.best_estimator_
y_pred_dt = best_model.predict(X_test_encoded)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

C:\Users\Naveenkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Naveenkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naveenkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Naveenkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Naveenkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'poisson', 'absolute_error'}. Got 'friedman_mse' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Naveenkumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [0.58638257 0.58638257 0.58638257 0.71446477 0.71437761 0.71470859
 0.74671835 0.74674795 0.74701295 0.72190984 0.71878699 0.72559197
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

Best Parameters: {'criterion': 'squared_error', 'max_depth': 7, 'min_samples_split': 10}
Best CV Score: 0.7470129474410052

In [46]:
best_idx = grid.best_index_
print(best_idx)

8

In [47]:
print("--- Model 1 (Decision Tree) Test Evaluation ---")
print("R2 Score :", r2_score(y_test, y_pred_dt))
print("MAE      :", mean_absolute_error(y_test, y_pred_dt))
print("MSE      :", mean_squared_error(y_test, y_pred_dt))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, y_pred_dt)))

--- Model 1 (Decision Tree) Test Evaluation ---
R2 Score : 0.7570914288013748
MAE      : 11553.148596774834
MSE      : 558825423.4730605
RMSE     : 23639.488646606984

In [48]:
result_df=pd.DataFrame(grid.cv_results_)
print(result_df)

    mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        2.810844      0.169371         0.002877        0.000419
1        3.016252      0.145577         0.003144        0.000810
2        3.015810      0.132078         0.003140        0.000388
3        3.097021      0.150007         0.002850        0.000401
4        3.116220      0.106594         0.003273        0.000812
5        3.029949      0.070379         0.002952        0.000125
6        3.249209      0.032994         0.002981        0.000185
7        3.491669      0.157724         0.003366        0.000504
8        3.322701      0.084239         0.002885        0.000306
9        4.002732      0.116577         0.003303        0.000205
10       3.951718      0.067244         0.003213        0.000324
11       3.969015      0.081981         0.003262        0.000197
12       0.004359      0.000116         0.000000        0.000000
13       0.004394      0.000155         0.000000        0.000000
14       0.004250      0.000220         0.000000        0.000000
15       0.004333      0.000139         0.000000        0.000000
16       0.004279      0.000283         0.000000        0.000000
17       0.004377      0.000190         0.000000        0.000000
18       0.004531      0.000108         0.000000        0.000000
19       0.004711      0.000164         0.000000        0.000000
20       0.004906      0.000225         0.000000        0.000000
21       0.004698      0.000154         0.000000        0.000000
22       0.004569      0.000170         0.000000        0.000000
23       0.004566      0.000221         0.000000        0.000000

   param_criterion  param_max_depth  param_min_samples_split  \
0    squared_error                3                        2
1    squared_error                3                        5
2    squared_error                3                       10
3    squared_error                5                        2
4    squared_error                5                        5
5    squared_error                5                       10
6    squared_error                7                        2
7    squared_error                7                        5
8    squared_error                7                       10
9    squared_error               10                        2
10   squared_error               10                        5
11   squared_error               10                       10
12    friedman_mse                3                        2
13    friedman_mse                3                        5
14    friedman_mse                3                       10
15    friedman_mse                5                        2
16    friedman_mse                5                        5
17    friedman_mse                5                       10
18    friedman_mse                7                        2
19    friedman_mse                7                        5
20    friedman_mse                7                       10
21    friedman_mse               10                        2
22    friedman_mse               10                        5
23    friedman_mse               10                       10

                                               params  split0_test_score  \
0   {'criterion': 'squared_error', 'max_depth': 3,...           0.569202
1   {'criterion': 'squared_error', 'max_depth': 3,...           0.569202
2   {'criterion': 'squared_error', 'max_depth': 3,...           0.569202
3   {'criterion': 'squared_error', 'max_depth': 5,...           0.715651
4   {'criterion': 'squared_error', 'max_depth': 5,...           0.715651
5   {'criterion': 'squared_error', 'max_depth': 5,...           0.714599
6   {'criterion': 'squared_error', 'max_depth': 7,...           0.741226
7   {'criterion': 'squared_error', 'max_depth': 7,...           0.743041
8   {'criterion': 'squared_error', 'max_depth': 7,...           0.741026
9   {'criterion': 'squared_error', 'max_depth': 10...           0.717567
10  {'criterion': 'squared_error', 'max_depth': 10...           0.709936
11  {'criterion': 'squared_error', 'max_depth': 10...           0.724789
12  {'criterion': 'friedman_mse', 'max_depth': 3, ...                NaN
13  {'criterion': 'friedman_mse', 'max_depth': 3, ...                NaN
14  {'criterion': 'friedman_mse', 'max_depth': 3, ...                NaN
15  {'criterion': 'friedman_mse', 'max_depth': 5, ...                NaN
16  {'criterion': 'friedman_mse', 'max_depth': 5, ...                NaN
17  {'criterion': 'friedman_mse', 'max_depth': 5, ...                NaN
18  {'criterion': 'friedman_mse', 'max_depth': 7, ...                NaN
19  {'criterion': 'friedman_mse', 'max_depth': 7, ...                NaN
20  {'criterion': 'friedman_mse', 'max_depth': 7, ...                NaN
21  {'criterion': 'friedman_mse', 'max_depth': 10,...                NaN
22  {'criterion': 'friedman_mse', 'max_depth': 10,...                NaN
23  {'criterion': 'friedman_mse', 'max_depth': 10,...                NaN

    split1_test_score  split2_test_score  split3_test_score  \
0            0.561126           0.600422           0.572994
1            0.561126           0.600422           0.572994
2            0.561126           0.600422           0.572994
3            0.689269           0.730699           0.702989
4            0.689269           0.730699           0.702888
5            0.689837           0.732253           0.703137
6            0.716702           0.772007           0.738751
7            0.715592           0.771981           0.738788
8            0.716860           0.773569           0.738859
9            0.691246           0.739721           0.708552
10           0.683869           0.736496           0.711585
11           0.692354           0.745223           0.714545
12                NaN                NaN                NaN
13                NaN                NaN                NaN
14                NaN                NaN                NaN
15                NaN                NaN                NaN
16                NaN                NaN                NaN
17                NaN                NaN                NaN
18                NaN                NaN                NaN
19                NaN                NaN                NaN
20                NaN                NaN                NaN
21                NaN                NaN                NaN
22                NaN                NaN                NaN
23                NaN                NaN                NaN

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0            0.628169         0.586383        0.024721               10
1            0.628169         0.586383        0.024721               10
2            0.628169         0.586383        0.024721               10
3            0.733717         0.714465        0.016746                8
4            0.733382         0.714378        0.016683                9
5            0.733716         0.714709        0.016862                7
6            0.764907         0.746718        0.019824                3
7            0.764337         0.746748        0.019969                2
8            0.764750         0.747013        0.020156                1
9            0.752463         0.721910        0.021855                5
10           0.752049         0.718787        0.023535                6
11           0.751049         0.725592        0.021265                4
12                NaN              NaN             NaN               13
13                NaN              NaN             NaN               13
14                NaN              NaN             NaN               13
15                NaN              NaN             NaN               13
16                NaN              NaN             NaN               13
17                NaN              NaN             NaN               13
18                NaN              NaN             NaN               13
19                NaN              NaN             NaN               13
20                NaN              NaN             NaN               13
21                NaN              NaN             NaN               13
22                NaN              NaN             NaN               13
23                NaN              NaN             NaN               13

In [50]:
from sklearn.decomposition import PCA

pca=PCA(
    n_components=2,
    random_state=42
)

X_train_pca=pca.fit_transform(X_train_encoded)
X_test_pca=pca.transform(X_test_encoded)

print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[0.1667678  0.08037377]
[273.6106304  189.94770364]

In [54]:
dt_pca=DecisionTreeRegressor(random_state=42)

param_grid = {
    'criterion': ['squared_error'],
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10]
}

grid_pca=GridSearchCV(
    estimator=dt_pca,
    param_grid=param_grid,
    cv=5,
    n_jobs=1,
    scoring="r2"
)

grid_pca.fit(X_train_pca,y_train)

print(grid_pca.best_estimator_)
print(grid_pca.cv_results_)
print(grid_pca.best_score_)

DecisionTreeRegressor(max_depth=5, random_state=42)
{'mean_fit_time': array([0.02916532, 0.02814198, 0.02820044, 0.04203811, 0.04178205,
       0.04264994, 0.05426922, 0.05499454, 0.05312152, 0.07010345,
       0.06872296, 0.06911354]), 'std_fit_time': array([0.00124548, 0.00015967, 0.0006998 , 0.00084392, 0.00044781,
       0.0010387 , 0.00088621, 0.00106323, 0.00147444, 0.00150997,
       0.00175204, 0.00204134]), 'mean_score_time': array([0.00258708, 0.00260825, 0.00252223, 0.0027494 , 0.00264153,
       0.00258536, 0.00294642, 0.00316982, 0.00291657, 0.00321407,
       0.00329332, 0.0032413 ]), 'std_score_time': array([9.96672933e-05, 9.97845301e-05, 2.76040656e-04, 1.75986597e-04,
       9.37961356e-05, 6.71691446e-05, 1.49069805e-04, 3.70608668e-04,
       1.08675781e-04, 1.09721401e-04, 1.16004730e-04, 1.61273842e-04]), 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                   'squared_error', 'squared_error', 'squared_error',
                   'squared_error', 'squared_error', 'squared_error',
                   'squared_error', 'squared_error', 'squared_error'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_max_depth': masked_array(data=[3, 3, 3, 5, 5, 5, 7, 7, 7, 10, 10, 10],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'param_min_samples_split': masked_array(data=[2, 5, 10, 2, 5, 10, 2, 5, 10, 2, 5, 10],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'params': [{'criterion': 'squared_error', 'max_depth': 3, 'min_samples_split': 2}, {'criterion': 'squared_error', 'max_depth': 3, 'min_samples_split': 5}, {'criterion': 'squared_error', 'max_depth': 3, 'min_samples_split': 10}, {'criterion': 'squared_error', 'max_depth': 5, 'min_samples_split': 2}, {'criterion': 'squared_error', 'max_depth': 5, 'min_samples_split': 5}, {'criterion': 'squared_error', 'max_depth': 5, 'min_samples_split': 10}, {'criterion': 'squared_error', 'max_depth': 7, 'min_samples_split': 2}, {'criterion': 'squared_error', 'max_depth': 7, 'min_samples_split': 5}, {'criterion': 'squared_error', 'max_depth': 7, 'min_samples_split': 10}, {'criterion': 'squared_error', 'max_depth': 10, 'min_samples_split': 2}, {'criterion': 'squared_error', 'max_depth': 10, 'min_samples_split': 5}, {'criterion': 'squared_error', 'max_depth': 10, 'min_samples_split': 10}], 'split0_test_score': array([0.44506412, 0.44506412, 0.44506412, 0.49860527, 0.49860527,
       0.49860527, 0.50037731, 0.49783751, 0.49946649, 0.43315319,
       0.43356586, 0.43948815]), 'split1_test_score': array([0.42655145, 0.42655145, 0.42655145, 0.46096625, 0.46096625,
       0.46096625, 0.45461096, 0.45421164, 0.45245094, 0.37699226,
       0.38226025, 0.3897357 ]), 'split2_test_score': array([0.44600917, 0.44600917, 0.44600917, 0.49940209, 0.49940209,
       0.49940209, 0.49060789, 0.49060789, 0.49086928, 0.42516476,
       0.43100541, 0.43607641]), 'split3_test_score': array([0.44286966, 0.44286966, 0.44286966, 0.4805197 , 0.4805197 ,
       0.4805197 , 0.47599192, 0.47669148, 0.47669144, 0.43232123,
       0.43780865, 0.43933516]), 'split4_test_score': array([0.48622618, 0.48622618, 0.48622618, 0.53429542, 0.53429542,
       0.53429542, 0.53970331, 0.53967329, 0.53971212, 0.47258735,
       0.47464976, 0.48571853]), 'mean_test_score': array([0.44934412, 0.44934412, 0.44934412, 0.49475775, 0.49475775,
       0.49475775, 0.49225828, 0.49180436, 0.49183806, 0.42804376,
       0.43185799, 0.43807079]), 'std_test_score': array([0.01975424, 0.01975424, 0.01975424, 0.02426598, 0.02426598,
       0.02426598, 0.02828989, 0.02818112, 0.02874656, 0.0304732 ,
       0.0294283 , 0.03037819]), 'rank_test_score': array([ 7,  7,  7,  1,  1,  1,  4,  6,  5, 12, 11, 10], dtype=int32)}
0.49475774643450593

In [55]:
y_pred_pca=grid_pca.predict(X_test_pca)
print(y_pred_pca)

[ 28758.19755429  42599.40670807  65904.26973684 ...  28758.19755429
  15093.02699648 136819.62957801]

In [56]:
print("--- Model 2 (Decision Tree) Test Evaluation ---")
print("R2 Score :", r2_score(y_test, y_pred_pca))
print("MAE      :", mean_absolute_error(y_test, y_pred_pca))
print("MSE      :", mean_squared_error(y_test, y_pred_pca))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, y_pred_pca)))

--- Model 2 (Decision Tree) Test Evaluation ---
R2 Score : 0.5067384145976455
MAE      : 23763.079564635984
MSE      : 1134777224.9669552
RMSE     : 33686.45462150856

In [57]:
print(grid_pca.best_estimator_)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [58]:
best_model1=grid.best_estimator_
best_model2=grid_pca.best_estimator_

scores1=cross_val_score(best_model1,X_train_encoded,y_train,cv=5,scoring="r2")
scores2=cross_val_score(best_model2,X_train_pca,y_train,cv=5,scoring="r2")

print("NO PCA:",scores1)

NO PCA: [0.74102632 0.71685993 0.77356896 0.73885932 0.76475021]

In [59]:
print("PCA:",scores2)

PCA: [0.49860527 0.46096625 0.49940209 0.4805197  0.53429542]

In [63]:
from scipy.stats import friedmanchisquare, f_oneway

model_scores=[scores1,scores2]
# Friedman Test (non-parametric)
anova_stat, anova_p = f_oneway(*model_scores)

if anova_p < 0.05:
    print("At least one model differs significantly")
else:
    print("No significant difference detected")

At least one model differs significantly

In [64]:
lr = LinearRegression()
scores3 = cross_val_score(lr, X_train_encoded, y_train, cv=5, scoring="r2")
print("Model 3 (Linear Regression) Fold Scores:", scores3)

model_scores = [scores1, scores2, scores3]

# Friedman Test (works because k = 3 >= 3)
friedman_stat, friedman_p = friedmanchisquare(*model_scores)
print(f"Friedman stat: {friedman_stat:.4f}, p: {friedman_p:.4f}")

if friedman_p < 0.05:
  print("Significant difference among models | proceed with post-hoc test")
else:
  print("No significant difference | all models perform similarly")

Model 3 (Linear Regression) Fold Scores: [0.57436225 0.53989944 0.58094498 0.56532463 0.61483096]
Friedman stat: 10.0000, p: 0.0067
Significant difference among models | proceed with post-hoc test

In [68]:
model_means = [np.mean(scores) for scores in model_scores]
best_index = np.argmax(model_means) # or np.argmin if lower is better
print(f"Best model: Model {best_index + 1} with mean score ={model_means[best_index]:.4f}")

Best model: Model 1 with mean score =0.7470

In [70]:
from scipy.stats import ttest_rel, wilcoxon, ttest_ind

# Model 1 vs. Model 2 validation fold scores
m1 = scores1
m2 = scores2

# 1. Paired t-test (Cheatsheet Sec 7)
paired_stat, paired_p = ttest_rel(m1, m2)
print(f"Paired t-test: stat = {paired_stat:.4f}, p = {paired_p:.4f}")
if paired_p < 0.05:
    print("Paired t-test: Significant difference (p < 0.05)")
else:
    print("Paired t-test: No significant difference")

# 2. Wilcoxon Signed-Rank Test (Cheatsheet Sec 7)
wilc_stat, wilc_p = wilcoxon(m1, m2)
print(f"\nWilcoxon test: stat = {wilc_stat:.4f}, p = {wilc_p:.4f}")
if wilc_p < 0.05:
    print("Wilcoxon: Significant difference (p < 0.05)")
else:
    print("Wilcoxon: No significant difference")

# 3. Independent t-test (Cheatsheet Sec 7)
ind_stat, ind_p = ttest_ind(m1, m2, equal_var=False)
print(f"\nIndependent t-test: stat = {ind_stat:.4f}, p = {ind_p:.4f}")
if ind_p < 0.05:
    print("Independent t-test: Significant difference")
else:
    print("Independent t-test: No significant difference")

Paired t-test: stat = 33.9778, p = 0.0000
Paired t-test: Significant difference (p < 0.05)

Wilcoxon test: stat = 0.0000, p = 0.0625
Wilcoxon: No significant difference

Independent t-test: stat = 15.9932, p = 0.0000
Independent t-test: Significant difference